COPY apache2-drupal.conf /etc/apache2/sites-available/drupal.conf

RUN set -xe && \
    a2ensite drupal && \
    a2dissite 000-default && \
    a2enmod rewrite && \
    mkdir -p /etc/apache2/conf-extra-enabled && \
    echo "IncludeOptional conf-extra-enabled/*.conf" >> /etc/apache2/apache2.conf && \
    true